- name: Tap into the Homebrew "cask-versions" repository
  community.general.homebrew_tap:
    name:
      - homebrew/cask-versions
      - localsend/localsend
    state: present

- name: Install specified Homebrew packages
  community.general.homebrew:
    name:
      - curl
      - docker
      - fd
      - gawk
      - gettext
      - gpg
      - gh
      - git
      - cmake
      - htop
      - lazygit
      - localsend
      - ninja
      - tree-sitter
      - ripgrep
      - tmux
      - mas
      - stow
      - zsh
    state: latest

- name: Install specific applications using Homebrew casks
  community.general.homebrew_cask:
    name:
      - alacritty
      - amneziavpn
      - chatgpt
      - discord
      - figma
      - google-chrome
      - iterm2-beta
      - karabiner-elements
      - nextcloud
      - obsidian
      - orbstack
      - outline
      - outline-manager
      - slack
      - soundsource
      - spotify
      - telegram
      - the-unarchiver
      - transmission
      - tuta-mail
      - visual-studio-code
      - vlc
      - wezterm
      - yandex
      - zed
    state: latest
  when: not ansible_env.GITHUB_ACTIONS | default("false") == "true"

- name: Install specific applications from Mac App Store
  community.general.mas:
    id:
      - 1352778147 # Bitwarden
      - 1291898086 # Toggle Track
      - 1451685025 # WireGuard
    state: latest
  when: not ansible_env.GITHUB_ACTIONS | default("false") == "true"
