- name: Install specified apt packages
  ansible.builtin.apt:
    name:
      - build-essential
      - checkinstall
      - curl
      - cmake
      - dirmngr
      - fd-find
      - fzf
      - gawk
      - gettext
      - gpg
      - gcc
      - g++
      - gh
      - git
      - htop
      - libyaml-dev
      - ninja-build
      - ripgrep
      - stow
      - tmux
      - unzip
      - xclip
      - zlib1g-dev
      - zsh
    state: latest
  become: true
