- name: Define cargo packages
  set_fact:
    cargo_packages:
      - starship

- name: Install cargo packages
  community.general.cargo:
    name: "{{ cargo_package_name }}"
    state: latest
  loop: "{{ cargo_packages }}"
  loop_control:
    loop_var: cargo_package_name
