"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$battery\
$time\
$character"""

[username]
show_always = true
format = "[$user]($style) at "
style_root = "bold red"
style_user = "cyan"

[hostname]
ssh_only = false
format = "[$hostname](yellow) "

[directory]
format = "in [$path](green) "

[git_branch]
format = "on [$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](red) ($ahead_behind $stashed)]($style) "
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "bright-yellow"

[time]
disabled = false
use_12hr = true
format = "[$time]($style) "
style = "none"

[character]
success_symbol = "[⌁](purple)"
error_symbol = "[⌁](red)"
vimcmd_symbol = "[v](green)"
