[colors]
ansi = [
  "#484f58", # black
  "#ff7b72", # red
  "#3fb950", # green
  "#d29922", # yellow
  "#58a6ff", # blue
  "#bc8cff", # magenta
  "#39c5cf", # cyan
  "#b1bac4", # white
]
background = "#0d1117"
brights = [
  "#6e7681", # bright black
  "#ffa198", # bright red
  "#56d364", # bright green
  "#e3b341", # bright yellow
  "#79c0ff", # bright blue
  "#d2a8ff", # bright magenta
  "#56d4dd", # bright cyan
  "#ffffff", # bright white
]
cursor_bg = "#2f81f7"
cursor_border = "#2f81f7"
cursor_fg = "#e6edf3"
foreground = "#e6edf3"
selection_bg = "rgba(47,129,247,0.2)"
selection_fg = "none"

[colors.indexed]

[metadata]
aliases = ["Github Dark Default"]
name = "Github Dark"
wezterm_version = "Always"
