import = [
  # "~/.config/alacritty/github-dark.toml",
  # "~/.config/alacritty/github-light.toml",
  "~/.config/alacritty/rasmus.toml",
]

[env]
TERM = 'xterm-256color'

[font]
normal = { family = 'Iosevka Nerd Font', style = 'Regular' }
size = 14

[scrolling]
history = 20_000

[window]
dynamic_padding = true
padding = { x = 5, y = 5 }
