- name: Tap into the Homebrew 'cask-fonts' repository
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install specific cask fonts and their nerd versions
  community.general.homebrew_cask:
    name:
      - "font-{{ item }}"
      - "font-{{ item }}-nerd-font"
    state: latest
  loop: "{{ [font] | flatten | map('replace', ' ', '-') | map('lower') }}"
